### ISSUE TITLE
Configureable Build Command

### ISSUE THREAD

**Issue by southpolesteve** [bustlelabs/shep#158]
Webpack is currently hardcoded as the build command (https://github.com/bustlelabs/shep/blob/master/src/util/build-functions.js#L4) but we could make this configureable. Would allow us to experiment with other build tools such as `rollup`

**Comment by chris-olszewski** [comment]
We should probably mention in the docs somewhere that altering the build command can (and probably will) break pattern matching

**Comment by southpolesteve** [comment]
Agreed. @chris-olszewski can you tackle this next? I want to play with using rollup for some of our simpler projects.
