### ISSUE TITLE
Proxy AWS context when running locally

### ISSUE THREAD

**Issue by zfoster** [bustlelabs/shep#164]
Would be amazing to have the full suite of AWS_LAMBDA process.env vars written as proxies when shep runs locally.

I'm running functions locally with wool, and functionName and functionVersion are null - which makes sense.

See here: https://github.com/bustlelabs/shep-logger/blob/master/bole.js#L6-L8

These and if there are any other obvious AWS ENV vars to add!

**Comment by southpolesteve** [comment]
Some prior art we may want to use or reference https://www.npmjs.com/package/aws-lambda-mock-context

**Comment by zfoster** [comment]
gonna start here

**Comment by zfoster** [comment]
Changed this to context, original issue here: https://github.com/bustlelabs/shep/issues/192
