### ISSUE TITLE
shep build in shep 3.x should ignore the --env flag

### ISSUE THREAD

**Issue by TSiege** [bustlelabs/shep#175]
currently it exhibits 2.x behavior and looks for a `./config/<env>.js` file then throws an error if it isn't there

**Comment by TSiege** [comment]
I now think this was a problem with the docs and should be just `shep build [function]`, doing it the way the docs say causes an error because there's hopefully no function named after an environment.

**Comment by chris-olszewski** [comment]
@TSiege you're completely right, I forgot to update the docs :slightly_frowning_face:

**Comment by southpolesteve** [comment]
Close by #182
