### ISSUE TITLE
More useful prompt for shep create-function

### ISSUE THREAD

**Issue by bigtiger** [bustlelabs/shep#44]
Provide some context in the prompt for the Lambda execution role in `shep create-function`.

``` bash
? Lambda execution role. This must already exist. See your IAM console for details shep-
user
 ⫸  Deploying foo-floodgate-io-rickroll2  Uploading to AWS       
Unhandled rejection ValidationException: 1 validation error detected: Value 'shep-user' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+
```

Give me an example of what that role is supposed to look like (e.g. `arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+` not the role name).

**Comment by southpolesteve** [comment]
@bigtiger shep will now accept a role name or create one for you on project setup. no need to provide a full ARN.
