### ISSUE TITLE
ES6 Webpack Config

### ISSUE THREAD

**Issue by gdub22** [bustlelabs/shep#70]
You can write webpack configs using ES6 and name the file `webpack.config.babel.js` and webpack knows to transpile it for you.

Looks like shep is looking up a hardcoded  `webpack.config.js` upon build.

May or may not have to make `babel-register` a dependency too.

**Comment by southpolesteve** [comment]
@gdub22 closed in beta.10. Since were just execing `webpack` as a child process this should just work
